"""Markdown + PDF export for chat sessions.

`session_to_markdown(session, messages) → str`
  Round-trips a SessionStore.ChatSession + its messages into a polished
  markdown research report. Drops `system` and `tool` rows; keeps user
  questions as `## 问题` headers and assistant answers verbatim. Adds a
  cover page with title / created_at / message count.

`markdown_to_pdf(md, *, title=None) → bytes`
  Pure-python markdown → HTML → PDF via xhtml2pdf. Activated by the
  `[export]` extra: `pip install "faro-research[export]"`. Raises
  RuntimeError if xhtml2pdf isn't installed (caller surfaces a helpful
  500 to the user).

Why xhtml2pdf and not weasyprint:
  - weasyprint needs Pango / Cairo / GDK-Pixbuf system libs (annoying on
    Alpine / non-glibc Docker bases)
  - xhtml2pdf is pure-python, ships in the wheel, runs anywhere
  - Output isn't pixel-perfect but plenty good for shareable research PDFs
"""

from __future__ import annotations

import logging
import re
from io import BytesIO
from typing import Any

log = logging.getLogger(__name__)


# ────────────────────────────────────────────────────────────────────────────
# Markdown assembly
# ────────────────────────────────────────────────────────────────────────────


def session_to_markdown(session: Any, messages: list[Any]) -> str:
    """Build a polished markdown doc from a session + its messages."""
    qa = [m for m in messages if m.role in ("user", "assistant")]
    n_q = sum(1 for m in qa if m.role == "user")
    parts: list[str] = [
        f"# {session.title}",
        "",
        f"_导出于 {session.updated_at.strftime('%Y-%m-%d %H:%M')} · "
        f"{n_q} 个问题 · 创建于 {session.created_at.strftime('%Y-%m-%d')}_",
        "",
        "---",
        "",
    ]
    q_idx = 0
    for m in qa:
        if m.role == "user":
            q_idx += 1
            parts.append(f"## 问题 {q_idx}")
            parts.append("")
            # Quote-style for the question
            for line in (m.content or "").splitlines():
                parts.append(f"> {line}")
            parts.append("")
        else:   # assistant
            parts.append(m.content or "(empty)")
            parts.append("")
            parts.append("---")
            parts.append("")
    parts.append("")
    parts.append("> Generated by [Faro Research](https://github.com/alonegg/faro-research)")
    return "\n".join(parts)


# ────────────────────────────────────────────────────────────────────────────
# Markdown → HTML (small in-house converter)
# ────────────────────────────────────────────────────────────────────────────


def _md_inline_to_html(text: str) -> str:
    """Bold / italic / code inline markup. Order matters."""
    # escape HTML first
    text = (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))
    # `code`
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # **bold**
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    # *italic*
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    return text


def _markdown_to_html(md: str) -> str:
    """Tiny markdown → HTML — only what session output uses.

    Supports: # / ## / ### headings, **bold** / *italic* / `code`,
    GFM tables (| … |), bullet/numbered lists, blockquotes, horizontal rules.
    """
    out: list[str] = []
    lines = md.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]

        # Horizontal rule
        if line.strip() in ("---", "***"):
            out.append("<hr/>")
            i += 1
            continue

        # Headings
        h = re.match(r"^(#{1,6})\s+(.*)$", line)
        if h:
            level = min(len(h.group(1)) + 1, 6)
            out.append(f"<h{level}>{_md_inline_to_html(h.group(2))}</h{level}>")
            i += 1
            continue

        # Tables: | … | header followed by | --- | separator
        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:|-]+\|", lines[i + 1]):
            header_cells = [c.strip() for c in line.strip().strip("|").split("|")]
            i += 2
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            tbl = ['<table cellpadding="4" cellspacing="0">']
            tbl.append("<thead><tr>" + "".join(
                f"<th>{_md_inline_to_html(c)}</th>" for c in header_cells
            ) + "</tr></thead>")
            tbl.append("<tbody>")
            for r in rows:
                tbl.append("<tr>" + "".join(
                    f"<td>{_md_inline_to_html(c)}</td>" for c in r
                ) + "</tr>")
            tbl.append("</tbody></table>")
            out.append("\n".join(tbl))
            continue

        # Bullet list
        if re.match(r"^\s*[-*]\s+", line):
            items = []
            while i < len(lines) and re.match(r"^\s*[-*]\s+", lines[i]):
                items.append(re.sub(r"^\s*[-*]\s+", "", lines[i]))
                i += 1
            out.append("<ul>" + "".join(
                f"<li>{_md_inline_to_html(x)}</li>" for x in items
            ) + "</ul>")
            continue

        # Numbered list
        if re.match(r"^\s*\d+\.\s+", line):
            items = []
            while i < len(lines) and re.match(r"^\s*\d+\.\s+", lines[i]):
                items.append(re.sub(r"^\s*\d+\.\s+", "", lines[i]))
                i += 1
            out.append("<ol>" + "".join(
                f"<li>{_md_inline_to_html(x)}</li>" for x in items
            ) + "</ol>")
            continue

        # Blockquote (single or multi-line)
        if line.startswith("> "):
            buf = []
            while i < len(lines) and lines[i].startswith("> "):
                buf.append(lines[i][2:])
                i += 1
            out.append(
                "<blockquote>" + "<br/>".join(
                    _md_inline_to_html(x) for x in buf
                ) + "</blockquote>"
            )
            continue

        # Blank line
        if line.strip() == "":
            i += 1
            continue

        # Plain paragraph (collect consecutive non-blank lines)
        buf = [line]
        i += 1
        while i < len(lines) and lines[i].strip() and not _is_block_start(lines[i]):
            buf.append(lines[i])
            i += 1
        out.append("<p>" + "<br/>".join(_md_inline_to_html(x) for x in buf) + "</p>")

    return "\n".join(out)


def _is_block_start(line: str) -> bool:
    if not line:
        return False
    if line.startswith("#") and re.match(r"^#{1,6}\s", line):
        return True
    if line.startswith("|") or line.strip() in ("---", "***"):
        return True
    if re.match(r"^\s*[-*]\s+", line) or re.match(r"^\s*\d+\.\s+", line):
        return True
    if line.startswith("> "):
        return True
    return False


_PDF_CSS = """
@page { size: A4; margin: 1.6cm 1.8cm; }
body { font-family: 'Helvetica', 'PingFang SC', 'STHeiti', sans-serif;
       font-size: 10pt; line-height: 1.55; color: #1d1c19; }
h1 { font-size: 18pt; margin: 0 0 6pt; }
h2 { font-size: 14pt; margin: 14pt 0 4pt; color: #2a2823; }
h3 { font-size: 12pt; margin: 10pt 0 3pt; color: #2a2823; }
h4 { font-size: 11pt; margin: 8pt 0 2pt; }
p, li { font-size: 10pt; margin: 3pt 0; }
strong { color: #000; font-weight: 700; }
code { font-family: 'Menlo', 'Courier New', monospace; font-size: 9pt;
       background: #f3f1ec; padding: 0 3px; }
table { border-collapse: collapse; margin: 6pt 0; }
th { background: #f3f1ec; font-weight: 600; text-align: left; }
th, td { border: 1px solid #e1ddd4; padding: 4pt 6pt; font-size: 9.5pt; }
blockquote { border-left: 3px solid #e1ddd4; padding-left: 8pt; margin: 6pt 0;
             color: #4a4843; font-style: italic; }
hr { border: 0; border-top: 1px solid #e1ddd4; margin: 12pt 0; }
"""


def markdown_to_pdf(md: str, *, title: str | None = None) -> bytes:
    """Render markdown → PDF bytes via xhtml2pdf. Raises RuntimeError if the
    optional dep is missing (caller surfaces a 500 with the install hint)."""
    try:
        from xhtml2pdf import pisa  # type: ignore
    except ImportError as e:
        raise RuntimeError(
            "PDF export requires xhtml2pdf. Install via "
            '`pip install "faro-research[export]"`'
        ) from e

    body_html = _markdown_to_html(md)
    full_html = (
        f"<!DOCTYPE html><html><head>"
        f"<meta charset='utf-8'><title>{title or 'Faro Research'}</title>"
        f"<style>{_PDF_CSS}</style>"
        f"</head><body>{body_html}</body></html>"
    )
    out = BytesIO()
    result = pisa.CreatePDF(src=full_html, dest=out, encoding="utf-8")
    if result.err:
        raise RuntimeError(f"PDF render failed: {result.err} errors")
    return out.getvalue()
